Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class StudyController : Controller
    {
        private string connectionString = "Data Source=DESKTOP-CJT3444\\SQLEXPRESS;Initial Catalog=UniversityPerformanceTracker;Integrated Security=True";

        public ActionResult Index()
        {
            List<StudySession> studySessions = GetAllStudySessions();

            ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name");
            ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name");
            return View(studySessions);
        }

        public ActionResult AddStudySession()
        {
            ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name");
            ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult AddStudySession(StudySession session)
        {
            if (ModelState.IsValid)
            {
                // Check if the subject ID exists in the Subjects table
                bool subjectExists = GetAllSubjects().Any(s => s.Id == session.SubjectId);

                if (!subjectExists)
                {
                    ModelState.AddModelError("SubjectId", "Subject does not exist.");
                    ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name");
                    ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name");
                    return View(session);
                }

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = "INSERT INTO StudySessions (UserId, SubjectId, StartTime, EndTime) VALUES (@UserId, @SubjectId, @StartTime, @EndTime)";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@UserId", session.UserId);
                        command.Parameters.AddWithValue("@SubjectId", session.SubjectId);
                        command.Parameters.AddWithValue("@StartTime", session.StartTime);
                        command.Parameters.AddWithValue("@EndTime", session.EndTime);

                        connection.Open();
                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name");
            ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name");
            return View(session);
        }


        public ActionResult EditStudySession(int id)
        {
            StudySession session = GetStudySessionById(id);
            if (session == null)
                return HttpNotFound();

            ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name", session.UserId);
            ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name", session.SubjectId);
            return View(session);
        }

        [HttpPost]
        public ActionResult EditStudySession(StudySession session)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = "UPDATE StudySessions SET UserId = @UserId, SubjectId = @SubjectId, StartTime = @StartTime, EndTime = @EndTime WHERE Id = @Id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@Id", session.Id);
                        command.Parameters.AddWithValue("@UserId", session.UserId);
                        command.Parameters.AddWithValue("@SubjectId", session.SubjectId);
                        command.Parameters.AddWithValue("@StartTime", session.StartTime);
                        command.Parameters.AddWithValue("@EndTime", session.EndTime);

                        connection.Open();
                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.Users = new SelectList(GetAllUsers(), "Id", "Name", session.UserId);
            ViewBag.Subjects = new SelectList(GetAllSubjects(), "Id", "Name", session.SubjectId);
            return View(session);
        }

        public ActionResult DeleteStudySession(int id)
        {
            StudySession session = GetStudySessionById(id);
            if (session != null)
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = "DELETE FROM StudySessions WHERE Id = @Id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@Id", id);

                        connection.Open();
                        command.ExecuteNonQuery();
                    }
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult WeeklyProgress()
        {
            var weeklyProgress = CalculateWeeklyProgress();
            return View(weeklyProgress);
        }

        private Dictionary<DateTime, List<(StudySession, string)>> CalculateWeeklyProgress()
        {
            var weeklyProgress = new Dictionary<DateTime, List<(StudySession, string)>>();
            var startDate = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek);
            var endDate = startDate.AddDays(6);

            List<StudySession> allSessions = GetAllStudySessions();

            for (var date = startDate; date <= endDate; date = date.AddDays(1))
            {
                var sessionsForDate = allSessions.Where(s => s.StartTime.Date == date).ToList();
                var activitiesForDate = sessionsForDate.Select(s =>
                {
                    var subjectName = GetAllSubjects().FirstOrDefault(sub => sub.Id == s.SubjectId)?.Name ?? "N/A";
                    return (s, subjectName);
                }).ToList();
                weeklyProgress[date] = activitiesForDate;
            }

            return weeklyProgress;
        }

        public ActionResult PredictedAcademicStatus()
        {
            double studyHours = CalculateTotalStudyHours();
            double beakHours = CalculateTotalBreakHours();
            var (predictedGrade, activeHours) = CalculatePredictedGrades(studyHours, beakHours);
            ViewBag.PredictedGrade = predictedGrade;
            ViewBag.ActiveHours = activeHours.ToString("F2");
            return View();
        }

        private List<Break> GetAllBreaks()
        {
            List<Break> breaks = new List<Break>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sql = "SELECT Id, UserId, StartTime, EndTime FROM Breaks";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Break breakSession = new Break
                            {
                                Id = (int)reader["Id"],
                                UserId = (int)reader["UserId"],
                                StartTime = (DateTime)reader["StartTime"],
                                EndTime = (DateTime)reader["EndTime"]
                            };
                            breaks.Add(breakSession);
                        }
                    }
                }
            }

            return breaks;
        }

        private double CalculateTotalBreakHours()
        {
            List<Break> allBreak = GetAllBreaks();
            double totalHours = allBreak.Sum(s => (s.EndTime - s.StartTime).TotalHours);
            return totalHours;
        }

        private double CalculateTotalStudyHours()
        {
            List<StudySession> allSessions = GetAllStudySessions();
            double totalHours = allSessions.Sum(s => (s.EndTime - s.StartTime).TotalHours);
            return totalHours;
        }

        private (string, double) CalculatePredictedGrades(double studyHours, double breakHours)
        {
            double activeHours = studyHours - breakHours;

            string predictedGrade;
            if (activeHours >= 40)
            {
                predictedGrade = "Excellent";
            }
            else if (activeHours >= 30)
            {
                predictedGrade = "Good";
            }
            else if (activeHours >= 20)
            {
                predictedGrade = "Average";
            }
            else
            {
                predictedGrade = "Below Average";
            }

            return (predictedGrade, activeHours);
        }


        private List<User> GetAllUsers()
        {
            List<User> users = new List<User>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sql = "SELECT Id, Name, Email, Password FROM Users";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    connection.Open();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            User user = new User
                            {
                                Id = (int)reader["Id"],

Views/Study/AddStudySession.cshtml
@model WebApplication1.Models.StudySession

@{ ViewBag.Title = "Add Study Session"; }

<h2>Add Study Session</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("UserId", (IEnumerable<SelectListItem>)ViewBag.Users, "Select User", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("SubjectId", (IEnumerable<SelectListItem>)ViewBag.Subjects, "Select Subject", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.StartTime, "{0:HH:mm}", new { @class = "form-control", type = "time" })
                            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.EndTime, "{0:HH:mm}", new { @class = "form-control", type = "time" })
                            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-primary" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Study/EditStudySession.cshtml
@model WebApplication1.Models.StudySession

@{ ViewBag.Title = "Edit Study Session"; }

<h2>Edit Study Session</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("UserId", (SelectList)ViewBag.Users, "Select User", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("SubjectId", (SelectList)ViewBag.Subjects, "Select Subject", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Study/Index.cshtml
@model IEnumerable<WebApplication1.Models.StudySession>

@{ ViewBag.Title = "Study Sessions";
    var subjects = ViewBag.Subjects as List<WebApplication1.Models.Subject>;
    var breaks = ViewBag.Breaks as List<WebApplication1.Models.Break>; }

<h2>Study Sessions</h2>

<p>
    @Html.ActionLink("Add New Study Session", "AddStudySession")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().EndTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var subjectName = subjects != null && subjects.Any() ? subjects.FirstOrDefault(s => s.Id == item.SubjectId)?.Name : "N/A";
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.UserName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SubjectId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StartTime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EndTime)
    </td>
    <td>
        @Html.ActionLink("Edit", "EditStudySession", new { id = item.Id }) |
        @Html.ActionLink("Delete", "DeleteStudySession", new { id = item.Id })
    </td>
</tr>
}
</table>

<h2>Breaks</h2>
<p>
    @Html.ActionLink("Break", "Index", "Breaks")
</p>


<h2>WeeklyProgress</h2>
<p>
    @Html.ActionLink("Weekly Progress", "WeeklyProgress")
</p>

<h2>Predicted Academic Status</h2>
<p>
    <!-- Example link to PredictedAcademicStatus -->
    @Html.ActionLink("Predicted Academic Status", "PredictedAcademicStatus", "Study")

</p>

Views/Study/PredictedAcademicStatus.cshtml
@{
    ViewBag.Title = "Predicted Academic Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Predicted Academic Status</h2>

@if (ViewBag.PredictedGrade != null)
{
    <p>Predicted Grade: @ViewBag.PredictedGrade</p>
    <p>Your active study hours this week: <strong>@ViewBag.ActiveHours</strong> hours</p>
}
else
{
    <p>No prediction available.</p>
}

Views/Study/WeeklyProgress.cshtml
@model Dictionary<DateTime, List<(WebApplication1.Models.StudySession, string)>>

@{ ViewBag.Title = "Weekly Progress"; }

<style>
    .table-container {
        width: 100%;
        margin-top: 20px;
    }

        .table-container table {
            width: 100%;
            border-collapse: collapse;
        }

        .table-container th, .table-container td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .table-container th {
            background-color: #f2f2f2;
        }
</style>

<h2>Weekly Progress</h2>

@foreach (var entry in Model)
{
<h3>@entry.Key.ToString("dddd, MMMM dd, yyyy")</h3>
                <div class="table-container">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Subject</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var tuple in entry.Value)
                            {
            <tr>
                <td>@tuple.Item1.UserName</td>
                <td>@tuple.Item2</td>
                <td>@tuple.Item1.StartTime.ToString("hh:mm tt")</td>
                <td>@tuple.Item1.EndTime.ToString("hh:mm tt")</td>
            </tr>                }
                        </tbody>
                    </table>
                </div>}